version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      root-dependencies:
        patterns: ['*']

  - package-ecosystem: npm
    directory: /examples/hello-card-spfx
    schedule:
      interval: weekly
    groups:
      spfx-canary-dependencies:
        patterns: ['*']

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
